# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

fastlane_version "1.12.0"

default_platform :ios

platform :ios do

  before_all do
  end

  desc "Increment build number"
  lane :increment_build do 
    increment_build_number
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    commit_version_bump(
      message: "Build number bump to #{build_number}",
      force: true
    )
  end

  desc "Runs snapshot"
  lane :snapshots do
    snapshot
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "riobus")
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :deploy do
    gym
    deliver
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "App Store Build #{build_number}")
  end

  after_all do |lane|
    notification(subtitle: "Lane #{lane} finished", message: ":)")
  end

  error do |lane, exception|
    notification(subtitle: "Lane #{lane} errored", message: exception)
  end
end
