# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s",
  "iPhone 6s Plus",
  "iPhone 5s",
  "iPhone 4s"
])

languages([
  'pt-BR'
])

# Where should the resulting screenshots be stored?
screenshots_path "./screenshots"

html_title 'RioBus iOS - Screenshots'

clear_previous_screenshots

# The name of the project's scheme
scheme 'riobus'

# Where is your project (or workspace)? Provide the full path here
project_path '../riobus.xcworkspace'

# By default, the latest version should be used automatically. If you want to change it, do it here
# ios_version '8.1'

custom_build_args "GCC_PREPROCESSOR_DEFINITIONS='$(inherited) SNAPSHOT=1'"


# Custom Callbacks

setup_for_device_change do |device, udid, language|
	puts "Running #{language} on #{device}"
end

teardown_device do |language, device|
   puts "Finished with #{language} on #{device}"
end
